"""Raw dataset loaders and the processed-dataset store.

Every loader returns a :class:`RawDataset`: a DataFrame of numeric feature columns
plus two metadata columns, ``label`` (normalised class name; benign traffic is mapped
to the configured benign label) and ``device`` (the IoT device the traffic was
captured on, or ``"all"`` when the dataset has no per-device information).

Supported datasets
------------------
* ``nbaiot``      N-BaIoT (Meidan et al., 2018) — primary dataset. Both the flat
                  layout (``1.benign.csv``, ``1.gafgyt.combo.csv``, ``1.mirai.ack.csv``…)
                  and the per-device folder layout (``Danmini_Doorbell/benign_traffic.csv``,
                  ``.../gafgyt_attacks/combo.csv``…) are recognised.
* ``ciciot2023``  CICIoT2023 CSV files (label column ``label``).
* ``ton_iot``     TON_IoT network dataset (label column ``type``).
* ``bot_iot``     Bot-IoT CSV files (label column ``category``).
* ``synthetic``   generated by :mod:`ppfl.data.synthetic` (testing only).
"""

from __future__ import annotations

import re
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any

import numpy as np
import pandas as pd

from ppfl.utils.config import Config
from ppfl.utils.logging import get_logger
from ppfl.utils.serialization import load_json, save_json
from ppfl.utils.seed import derive_seed

LOGGER = get_logger(__name__)

LABEL_COL = "label"
DEVICE_COL = "device"
META_COLS = (LABEL_COL, DEVICE_COL)

_ALIASES = {
    "nbaiot": "nbaiot",
    "n_baiot": "nbaiot",
    "ciciot2023": "ciciot2023",
    "ciciot": "ciciot2023",
    "toniot": "ton_iot",
    "ton_iot": "ton_iot",
    "botiot": "bot_iot",
    "bot_iot": "bot_iot",
    "synthetic": "synthetic",
}

NBAIOT_DEVICES = {
    "1": "Danmini_Doorbell",
    "2": "Ecobee_Thermostat",
    "3": "Ennio_Doorbell",
    "4": "Philips_B120N10_Baby_Monitor",
    "5": "Provision_PT_737E_Security_Camera",
    "6": "Provision_PT_838_Security_Camera",
    "7": "Samsung_SNH_1011_N_Webcam",
    "8": "SimpleHome_XCS7_1002_WHT_Security_Camera",
    "9": "SimpleHome_XCS7_1003_WHT_Security_Camera",
}

# Defaults for the generic tabular loaders; any key can be overridden with
# ``data.loader_options`` in the YAML configuration.
TABULAR_PRESETS: dict[str, dict[str, Any]] = {
    "ciciot2023": {
        "label_column": "label",
        "benign_values": ["BenignTraffic", "Benign", "BENIGN"],
        "device_column": None,
        "drop_columns": [],
        "file_glob": "**/*.csv",
    },
    "ton_iot": {
        "label_column": "type",
        "benign_values": ["normal"],
        "device_column": None,
        "drop_columns": ["ts", "src_ip", "dst_ip", "src_port", "dst_port", "label"],
        "file_glob": "**/*.csv",
    },
    "bot_iot": {
        "label_column": "category",
        "benign_values": ["Normal", "normal"],
        "device_column": None,
        "drop_columns": [
            "pkSeqID", "stime", "ltime", "saddr", "daddr", "sport", "dport",
            "seq", "attack", "subcategory", "smac", "dmac", "soui", "doui", "sco", "dco",
        ],
        "file_glob": "**/*.csv",
    },
}

_NBAIOT_IGNORED = {"features.csv", "data_summary.csv", "device_info.csv"}
_FLAT_NBAIOT = re.compile(r"^(\d+)\.(benign|gafgyt|mirai)(?:\.([a-z_]+))?\.csv$", re.IGNORECASE)


def canonical_dataset_name(name: str) -> str:
    """Normalise user-facing dataset names (``nbaIoT``, ``N-BaIoT``…) to canonical ids."""
    key = re.sub(r"[^a-z0-9_]", "", name.lower().replace("-", "_"))
    if key not in _ALIASES:
        raise ValueError(f"Unknown dataset {name!r}; supported: {sorted(set(_ALIASES.values()))}")
    return _ALIASES[key]


def normalise_label(value: str) -> str:
    return re.sub(r"[^a-z0-9]+", "_", str(value).strip().lower()).strip("_")


@dataclass
class RawDataset:
    frame: pd.DataFrame
    feature_columns: list[str]
    source_files: list[str] = field(default_factory=list)

    def class_counts(self) -> dict[str, int]:
        return self.frame[LABEL_COL].value_counts().to_dict()


def _cap_rows(df: pd.DataFrame, cap: int | None, seed: int) -> pd.DataFrame:
    if cap is None or len(df) <= cap:
        return df
    return df.sample(n=cap, random_state=seed % (2**32))


# --------------------------------------------------------------------------------------
# N-BaIoT
# --------------------------------------------------------------------------------------


def _nbaiot_file_index(raw_dir: Path) -> list[tuple[Path, str, str]]:
    """Return ``(path, device, label)`` for every N-BaIoT traffic CSV under ``raw_dir``."""
    entries: list[tuple[Path, str, str]] = []
    for path in sorted(raw_dir.rglob("*.csv")):
        name = path.name.lower()
        if name in _NBAIOT_IGNORED:
            continue
        flat = _FLAT_NBAIOT.match(path.name)
        if flat:
            dev_id, family, attack = flat.groups()
            device = NBAIOT_DEVICES.get(dev_id, f"device_{dev_id}")
            label = "benign" if family.lower() == "benign" else f"{family.lower()}_{attack.lower()}"
            entries.append((path, device, label))
            continue
        parent = path.parent.name.lower()
        if name == "benign_traffic.csv":
            entries.append((path, path.parent.name, "benign"))
        elif parent in ("gafgyt_attacks", "mirai_attacks"):
            family = parent.split("_")[0]
            entries.append((path, path.parent.parent.name, f"{family}_{normalise_label(path.stem)}"))
    return entries


def load_nbaiot(raw_dir: Path, cfg: Config) -> RawDataset:
    entries = _nbaiot_file_index(raw_dir)
    if not entries:
        raise FileNotFoundError(
            f"No N-BaIoT CSV files found under {raw_dir}. Download the dataset (see data/README.md), "
            "extract it there, or pass --raw-dir. Expected files like '1.benign.csv' / "
            "'1.mirai.ack.csv' or '<Device>/benign_traffic.csv'."
        )
    frames, feature_cols = [], None
    for path, device, label in entries:
        df = pd.read_csv(path, dtype=np.float32)
        cap = cfg.data.max_benign_samples_per_group if label == "benign" else cfg.data.max_samples_per_group
        df = _cap_rows(df, cap, derive_seed(cfg.experiment.seed, "nbaiot", device, label))
        if feature_cols is None:
            feature_cols = list(df.columns)
        elif list(df.columns) != feature_cols:
            common = [c for c in feature_cols if c in df.columns]
            LOGGER.warning("Column mismatch in %s; keeping %d common columns", path.name, len(common))
            feature_cols = common
        df[LABEL_COL] = label
        df[DEVICE_COL] = device
        frames.append(df)
        LOGGER.info("Loaded %-45s device=%-42s label=%-16s rows=%d", path.name, device, label, len(df))
    assert feature_cols is not None
    frame = pd.concat([f[feature_cols + list(META_COLS)] for f in frames], ignore_index=True)
    return RawDataset(frame, feature_cols, [str(p) for p, _, _ in entries])


# --------------------------------------------------------------------------------------
# Generic tabular datasets (CICIoT2023, TON_IoT, Bot-IoT)
# --------------------------------------------------------------------------------------


def load_tabular(raw_dir: Path, cfg: Config, dataset: str) -> RawDataset:
    opts = {**TABULAR_PRESETS[dataset], **cfg.data.loader_options}
    files = sorted(raw_dir.glob(opts["file_glob"]))
    if opts.get("max_files"):
        files = files[: int(opts["max_files"])]
    if not files:
        raise FileNotFoundError(f"No CSV files matching {opts['file_glob']!r} under {raw_dir} (see data/README.md)")
    label_col, device_col = opts["label_column"], opts.get("device_column")
    benign = {str(v) for v in opts["benign_values"]}
    drop = set(opts.get("drop_columns", []))
    cap_attack = cfg.data.max_samples_per_group
    cap_benign = cfg.data.max_benign_samples_per_group
    taken: dict[str, int] = {}
    kept: list[pd.DataFrame] = []
    rng_seed = derive_seed(cfg.experiment.seed, dataset, "chunks")
    for path in files:
        for chunk in pd.read_csv(path, chunksize=250_000, low_memory=False):
            chunk.columns = [str(c).strip() for c in chunk.columns]
            if label_col not in chunk.columns:
                raise KeyError(f"Label column {label_col!r} missing from {path}; set data.loader_options.label_column")
            labels = chunk[label_col].astype(str).str.strip()
            chunk[LABEL_COL] = np.where(labels.isin(benign), cfg.data.benign_label, labels.map(normalise_label))
            chunk[DEVICE_COL] = chunk[device_col].astype(str) if device_col else "all"
            for label, group in chunk.groupby(LABEL_COL, sort=False):
                cap = cap_benign if label == cfg.data.benign_label else cap_attack
                remaining = None if cap is None else cap - taken.get(label, 0)
                if remaining is not None and remaining <= 0:
                    continue
                if remaining is not None and len(group) > remaining:
                    group = group.sample(n=remaining, random_state=rng_seed % (2**32))
                taken[label] = taken.get(label, 0) + len(group)
                kept.append(group)
        LOGGER.info("Read %s (running class counts: %s)", path.name, dict(sorted(taken.items())))
    frame = pd.concat(kept, ignore_index=True)
    excluded = drop | {label_col, LABEL_COL, DEVICE_COL} | ({device_col} if device_col else set())
    features = [c for c in frame.columns if c not in excluded]
    numeric = frame[features].apply(pd.to_numeric, errors="coerce")
    numeric = numeric.loc[:, numeric.notna().any()]
    dropped = sorted(set(features) - set(numeric.columns))
    if dropped:
        LOGGER.info("Dropping %d non-numeric columns: %s", len(dropped), dropped)
    out = pd.concat([numeric.astype(np.float32), frame[[LABEL_COL, DEVICE_COL]]], axis=1)
    return RawDataset(out, list(numeric.columns), [str(p) for p in files])


# --------------------------------------------------------------------------------------
# Dispatch + processed store
# --------------------------------------------------------------------------------------


def load_raw_dataset(cfg: Config, raw_dir: Path | None = None) -> RawDataset:
    """Load the dataset named in ``cfg.data.dataset`` from ``raw_dir``."""
    dataset = canonical_dataset_name(cfg.data.dataset)
    raw_dir = Path(raw_dir) if raw_dir is not None else cfg.raw_dir
    if dataset == "synthetic":
        from ppfl.data.synthetic import generate_synthetic_traffic

        frame = generate_synthetic_traffic(cfg.data.synthetic, derive_seed(cfg.experiment.seed, "synthetic"))
        raw_dir.mkdir(parents=True, exist_ok=True)
        frame.to_csv(raw_dir / "synthetic_iot.csv", index=False)
        features = [c for c in frame.columns if c not in META_COLS]
        return RawDataset(frame, features, [str(raw_dir / "synthetic_iot.csv")])
    if not raw_dir.exists():
        raise FileNotFoundError(f"Raw data directory {raw_dir} does not exist (see data/README.md)")
    if dataset == "nbaiot":
        return load_nbaiot(raw_dir, cfg)
    return load_tabular(raw_dir, cfg, dataset)


PROCESSED_FILE = "cleaned.parquet"
METADATA_FILE = "metadata.json"


def save_processed(frame: pd.DataFrame, metadata: dict[str, Any], out_dir: Path) -> None:
    out_dir.mkdir(parents=True, exist_ok=True)
    frame.to_parquet(out_dir / PROCESSED_FILE, index=False)
    save_json(metadata, out_dir / METADATA_FILE)


def load_processed(out_dir: Path) -> tuple[pd.DataFrame, dict[str, Any]]:
    path = out_dir / PROCESSED_FILE
    if not path.exists():
        raise FileNotFoundError(
            f"Processed dataset not found at {path}. Run `python scripts/prepare_data.py "
            f"--dataset {out_dir.name}` first (or `--synthetic` for the test dataset)."
        )
    frame = pd.read_parquet(path)
    metadata = load_json(out_dir / METADATA_FILE) if (out_dir / METADATA_FILE).exists() else {}
    return frame, metadata
